### ISSUE TITLE
Adapt "About" section of repo

### ISSUE THREAD

**Issue by JakobMiksch** [qgis/qgis-docker#98]
The "About" section of the repo currently shows:

> Our way of running QGIS 3 server inside Docker

It would be more understandable to name it something like

> Official Docker image for QGIS Server and Desktop

![image](https://github.com/qgis/qgis-docker/assets/15704517/7b499336-d91b-4281-a4ac-9e65bff58965)

**Comment by 3nids** [comment]
fixed, thanks
